jobs:
  new-main:
    settings:
        slack:
            channel: [SUCCESS]
    requires: [~pr, ~commit]
    image: node:12
    steps:
      - dummy: echo "dummy"
      - meta: meta dump > $SD_ARTIFACTS_DIR/meta.json
