jobs:
  new-main:
    annotations:
      screwdriver.cd/buildTimeout: 1
    settings:
        slack:
            channel: [SUCCESS]
    requires: [~pr, ~commit]
    image: node:12
    steps:
      - dummy: echo "dummy"
      - meta: meta dump > $SD_ARTIFACTS_DIR/meta.json
      - env: export FACTORY_BUILD_STATUS=success
      - sleep: while true; do sleep 1; echo "sleep"; done
#      - dummy-2: echo "dummy 2"
      - teardown-first: |
          echo "first"
          sleep 1m
      - teardown-env: echo $FACTORY_BUILD_STATUS
