jobs:
  job-pr:
    requires: [~pr]
    image: node:12
    steps:
      - dummy: echo "dummy"
  new-main:
    annotations:
      screwdriver.cd/timeout: 1
    requires: [~pr, ~commit]
    image: node:12
    steps:
      - dummy: echo "dummy"
      - token: |
          curl -H "Authorization: Bearer $SD_TOKEN" $SD_SONAR_AUTH_URL
      - meta: meta dump > $SD_ARTIFACTS_DIR/meta.json
      - env: |
          export FACTORY_BUILD_STATUS=success
          env
      - sleep: |
          export ABORT_BUILD_STATUS=aborted
          while true; do sleep 1; echo "sleep"; done
#      - dummy-2: echo "dummy 2"
      - teardown-first: |
          echo "first"
          sleep 10m
      - teardown-env: |
          echo $FACTORY_BUILD_STATUS
          echo $ABORT_BUILD_STATUS
